name: "Release custom NixOS ISO"
on:
  push:
    tags:
      - v*
  workflow_dispatch: null
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check free space
        run: |
          echo "Free space:"
          df -h

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.beeserver-iso.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          name: nixos.iso
          path: nixos.iso

  release:
    needs:
      - build-iso
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download ISO
        uses: actions/download-artifact@v8
        with:
          name: nixos.iso
          path: .

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            nixos.iso